name: Build and Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  IMAGE_NAME: luna1560/stella-trip

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Build jar with Maven
        working-directory: ./back_end
        run: mvn clean package -DskipTests

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:latest_stellatrip ./back_end

      - name: Push Docker image to Docker Hub
        run: docker push $IMAGE_NAME:latest_stellatrip

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            IMAGE_NAME="${{ secrets.DOCKER_IMAGE_NAME }}"

            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            docker pull $IMAGE_NAME:latest_stellatrip

            docker stop app || true
            docker rm app || true

            docker run -d --name app \
              --network app-network \
              -e SPRING_PROFILES_ACTIVE=prod \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              -e DB_URL=${{ secrets.DB_URL }} \
              -e DB_USER=${{ secrets.DB_USER }} \
              -e jwt_key=${{ secrets.JWT_KEY }} \
              -e REDIS_HOST=${{ secrets.REDIS_HOST }} \
              -e REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }} \
              -e REDIS_PORT=${{ secrets.REDIS_PORT }} \
              -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
              -p 8080:8080 $IMAGE_NAME:latest_stellatrip
